name: Deploy Only Changed Files

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  detect-and-prepare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Needed to access previous commit

    - name: Detect changed files (safe for first commit)
      id: detect
      run: |
        echo "Recent commits:"
        git log -2 --oneline || echo "Only one commit found"

        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "Total commits: $COMMIT_COUNT"

        if [ "$COMMIT_COUNT" -eq 1 ]; then
          echo "First commit detected. Listing all files."
          git ls-files > changed_files.txt
        else
          echo "Using git diff to detect changed files"
          git diff --name-only HEAD^ HEAD > changed_files.txt
        fi

        echo "Changed files:"
        cat changed_files.txt || echo "No changes detected."

    - name: Copy only changed files to deploy folder
      run: |
        mkdir -p deploy
        while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            echo "Copying $file"
            mkdir -p "deploy/$(dirname "$file")"
            cp "$file" "deploy/$file"
          fi
        done < changed_files.txt

    - name: Show contents of deploy folder
      run: |
        echo "Files ready for deployment:"
        find deploy || echo "No files copied."

    - name: Upload deploy folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: deploy-folder
        path: deploy/
